steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/river-tiger-480716-d6/docker-repo/panda-app:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/river-tiger-480716-d6/docker-repo/panda-app:latest'
      - '.'

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/river-tiger-480716-d6/docker-repo/panda-app'

  # Step 3: Deploy to Cloud Run (FREE TIER OPTIMIZED!)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'panda-app'
      - '--image=us-central1-docker.pkg.dev/river-tiger-480716-d6/docker-repo/panda-app:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--max-instances=3'
      - '--min-instances=0'
      - '--concurrency=80'
      - '--cpu-throttling'
      - '--timeout=60'

# Store images in Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/river-tiger-480716-d6/docker-repo/panda-app:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/river-tiger-480716-d6/docker-repo/panda-app:latest'

# Use default machine (FREE tier)
options:
  machineType: 'UNSPECIFIED'
  logging: 'CLOUD_LOGGING_ONLY'